[package]
name = "rbrt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
rand = "0.8.0"
indicatif = "0.17.2"
image = "^0.24.0" 
tobj = "3.0.1" 
json = "0.12.4"
